apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: arunlazercoder/my-react-app:v1.0.1
        ports:
        - containerPort: 80